adding first unittest part
measure-your-life-squad/measure-your-life pull request #22
Opened 2020-04-30 20:59 UTC by wojtekesz

intro for activities unit test
include parse_to_utc and convert_to_utc methods
does not include post and get methods that require mock (probably)

2020-05-01 12:14 UTC, thegreatmoonmoon requested changes
@wojtekesz Have you tried to run those tests with pytest? they fail unfortunately :smile:

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +from api_backend_server.web_app.apis.activities import _convert_unix_to_iso8610, _parse_to_utc_iso8610
Name of test modules needs to start with `test_`. Can we change the file name from:
`pytest_activities_apis.py`
to:
`test_activities_apis.py`
?

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +from api_backend_server.web_app.apis.activities import create_activity, get_user_activities
for long imports ( > 88 characters) we can write them like that:
```python
from api_backend_server.web_app.apis.activities import (
    _convert_unix_to_iso8610,
    _parse_to_utc_iso8610,
)
```

Or, if we want all attributes to be imported to the test, a wild import in this case will also be acceptable:
```python
from api_backend_server.web_app.apis.activities import *
```

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +import mock as mock
mocks are not used in the test at the moment - let's not import them if not necessary :dog:

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +def test__parse_to_utc_iso8610_should_succeed():
Test fails - you are comparing a datetime object with a string, so assert will fail :stuck_out_tongue:

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +    # given
Those comments (given, when, then) are unnecessary imo for this test (may be useful for the tests that conform to that pattern though)

2020-05-01 12:14 UTC, thegreatmoonmoon commented on api_backend_server/tests/unit_tests/pytest_activities_apis.py
> +# NOT FINISHED TEST METHOD
We shouldn't commit commented out blocks of code - you could use a pytest fixture [skip](https://docs.pytest.org/en/latest/reference.html#pytest-skip) to temporarily skip unfinished test

2020-05-15 19:24 UTC, Qamas95 approved these changes
:octocat:

2020-05-15 19:25 UTC, thegreatmoonmoon approved these changes
:field_hockey: fixed

2020-05-15 19:25 UTC, merged